### ISSUE TITLE
Allow user to specify Trino Connection object conn and cur

### ISSUE THREAD

**Issue by mrhopko** [CybercentreCanada/jupyterlab-sql-editor#13]
A user may want to specify their own Trino connection in a notebook and add this to the Trino configuration. Presently the Trino configuration does not allow specifying the conn and cur attributes.

**Comment by cccs-jc** [comment]
A user can configure the magic via %config, for example

```
%config Trino.host='localhost'
%config Trino.port=8080
%config Trino.httpScheme='http'
%config Trino.auth=None
%config Trino.user='the-user'
```

Are there missing options.

**Comment by mrhopko** [comment]
Catalog and schema could be included and would be useful given issues with the Trino python connection not persisting session info (such as USE catalog.schema).

**Comment by cccs-jc** [comment]
okay sounds good. I'll add these configurations. At least a user will be able to switch default catalogs using this approach. A stop gap until the library properly handles USE.

**Comment by cccs-jc** [comment]
added two additional configs to the magic

%config Trino.catalog="cat1"
%config Trino.schema="schema2"

**Comment by cccs-jc** [comment]
fixed
