### ISSUE TITLE
trino magic: verify connection argument for adding certificate file path

### ISSUE THREAD

**Issue by sqlreport** [CybercentreCanada/jupyterlab-sql-editor#47]
https://github.com/CybercentreCanada/jupyterlab-sql-editor/blob/a22ca902ac6fa5ab14f3306363c0c52dfb97fa8e/jupyterlab_sql_editor/ipython_magic/trino/trino.py#L65-L72

Can we add `verify` connection argument for adding certificate file path?

**Comment by cccs-jc** [comment]
yes, that's a good idea. Do you want to create a PR and we will review and incorporate it. Thanks!
