### ISSUE TITLE
Auto completion does not work both on Windows 10 and ubuntu?

### ISSUE THREAD

**Issue by pltf492325129** [CybercentreCanada/jupyterlab-sql-editor#80]
Autocomplete does not work on Windows 10 or ubuntu
![image](https://user-images.githubusercontent.com/49930095/218767426-19974c7d-c263-4268-8518-07607f199ea9.png)

**Comment by pltf492325129** [comment]
How should I configure to use autocomplete

**Comment by cccs-nik** [comment]
@pltf492325129 https://github.com/CybercentreCanada/jupyterlab-sql-editor/blob/f9c353346ad1ad0b97307b8448d57234c3bf4536/overrides/sparksql-lsp.json#L19 For sparksql for example you would configure it here. That _should_ work but I just reworked the sourcing of the package to pick it up from nvm installs if that was your issue.

**Comment by pltf492325129** [comment]
Thank u very much

**Comment by pltf492325129** [comment]
But I have another problem, which is that the code cannot complete table name or tabel info.
